[package]
name = "perfetto-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.4"
#prost = { path = "../../src/prost/prost"}
prost-build = "0.12.4"
